"""Generate all section blocks and inject into pages."""
import os
os.makedirs('solucoes/_blocks', exist_ok=True)

I = {  # icons
    'star': '<polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>',
    'ppl': '<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="9" cy="7" r="4"></circle><path d="M23 21v-2a4 4 0 0 0-3-3.87"></path><path d="M16 3.13a4 4 0 0 1 0 7.75"></path>',
    'cam': '<rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><circle cx="12" cy="12" r="3"></circle><path d="M8 4V2"></path><path d="M16 4V2"></path>',
    'clk': '<circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>',
    'shd': '<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>',
    'chk': '<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline>',
    'spk': '<path d="M12 19l7-7 3 3-7 7-3-3z"></path><path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"></path><path d="M2 2l7.586 7.586"></path><circle cx="11" cy="11" r="2"></circle>',
    'hom': '<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path><polyline points="9 22 9 12 15 12 15 22"></polyline>',
    'map': '<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle>',
    'gft': '<polyline points="20 12 20 22 4 22 4 12"></polyline><rect x="2" y="7" width="20" height="5"></rect><line x1="12" y1="22" x2="12" y2="7"></line><path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z"></path><path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z"></path>',
}
def si(p,c="sc-solution-icon",s=24): return f'<svg class="{c}" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" viewBox="0 0 24 24">{p}</svg>'
def sc(icon,title,desc): return f'<div class="sc-solution-card">{si(icon)}<h3>{title}</h3><p>{desc}</p></div>'
def bc(icon,title,desc): return f'<div class="sc-benefit-card">{si(icon,"sc-benefit-icon",40)}<h3 class="sc-benefit-title">{title}</h3><p class="sc-benefit-text">{desc}</p></div>'
def gi(src,alt,w=1024,h=1024):
    lb=alt.split("—")[0].strip()if"—"in alt else alt[:40]
    return f'<div class="sc-gallery-card"><img src="{src}" alt="{alt}" width="{w}" height="{h}" loading="lazy"><div class="sc-gallery-card-label">{lb}</div></div>'
def gp(p,lb): return f'<div class="sc-gallery-card sc-gallery-placeholder">{si(p,"sc-solution-icon",24)}<span>[Imagem: {lb}]</span></div>'
def fq(q,a): return f'<div class="sc-faq-item"><button class="sc-faq-question" aria-expanded="false">{q}<svg class="sc-faq-icon" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg></button><div class="sc-faq-answer"><div class="sc-faq-answer-inner">{a}</div></div></div>'
FS='<script>(function(){var f=document.querySelector(".sc-faq-section");if(!f)return;f.querySelectorAll(".sc-faq-question").forEach(function(b){b.addEventListener("click",function(){var i=this.parentElement;var a=i.classList.contains("active");f.querySelectorAll(".sc-faq-item").forEach(function(x){x.classList.remove("active")});if(!a){i.classList.add("active");this.setAttribute("aria-expanded","true")}else{this.setAttribute("aria-expanded","false")}})})})();</script>'

CSS_S='<style>.sc-solutions-section{position:relative;width:100%;background:linear-gradient(180deg,#0a0102 0%,#1a0304 50%,#0a0102 100%);padding:80px 0}.sc-solutions-container{width:100%;max-width:1280px;margin:0 auto;padding:0 40px;box-sizing:border-box}.sc-solutions-eyebrow{font-family:Inter,sans-serif;font-size:13px;font-weight:700;letter-spacing:.15em;color:#F2B84B;text-transform:uppercase;text-align:center;margin-bottom:12px}.sc-solutions-title{font-family:var(--mfn-heading-font-family,Cinzel,serif);font-size:clamp(24px,3vw,36px);font-weight:700;color:#fff;line-height:1.2;margin:0 0 56px 0;text-align:center}.sc-solutions-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.sc-solution-card{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:32px 24px;transition:all .3s ease;display:flex;flex-direction:column;height:100%;box-sizing:border-box}.sc-solution-card:hover{background:rgba(255,255,255,.06);border-color:rgba(242,184,75,.3);transform:translateY(-4px)}.sc-solution-icon{color:var(--ca-gold-500,#F2B84B);width:36px;height:36px;margin-bottom:20px;flex-shrink:0}.sc-solution-card h3{font-family:Inter,sans-serif;font-size:14px;font-weight:700;color:#fff;text-transform:uppercase;letter-spacing:.06em;margin:0 0 12px 0;line-height:1.3}.sc-solution-card p{font-family:Inter,sans-serif;font-size:14px;line-height:1.6;color:rgba(255,255,255,.6);margin:0}@media(max-width:1024px){.sc-solutions-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:768px){.sc-solutions-section{padding:60px 0}.sc-solutions-container{padding:0 20px}.sc-solutions-grid{grid-template-columns:1fr}.sc-solutions-title{margin-bottom:40px}}</style>'
CSS_B='<style>.sc-benefits-section{position:relative;width:100%;background:linear-gradient(180deg,#0a0102 0%,#1a0304 50%,#0a0102 100%);padding:80px 0}.sc-benefits-container{width:100%;max-width:1280px;margin:0 auto;padding:0 40px;box-sizing:border-box}.sc-benefits-title{font-family:var(--mfn-heading-font-family,Cinzel,serif);font-size:clamp(24px,3vw,36px);font-weight:700;color:#fff;line-height:1.2;margin:0 0 56px 0;text-align:center}.sc-benefits-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:24px}.sc-benefit-card{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:32px 24px;text-align:center;transition:all .3s ease;display:flex;flex-direction:column;align-items:center;height:100%;box-sizing:border-box}.sc-benefit-card:hover{background:rgba(255,255,255,.06);border-color:rgba(242,184,75,.3);transform:translateY(-4px)}.sc-benefit-icon{color:var(--ca-gold-500,#F2B84B);width:40px;height:40px;margin-bottom:20px;flex-shrink:0}.sc-benefit-title{font-family:Inter,sans-serif;font-size:14px;font-weight:700;color:#fff;text-transform:uppercase;letter-spacing:.06em;margin:0 0 12px 0;line-height:1.3}.sc-benefit-text{font-family:Inter,sans-serif;font-size:14px;line-height:1.6;color:rgba(255,255,255,.6);margin:0}@media(max-width:1024px){.sc-benefits-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:768px){.sc-benefits-section{padding:60px 0}.sc-benefits-container{padding:0 20px}.sc-benefits-title{margin-bottom:40px}.sc-benefits-grid{grid-template-columns:1fr}}</style>'
CSS_G='<style>.sc-gallery-section{position:relative;width:100%;background:linear-gradient(180deg,#0a0102 0%,#1a0304 60%,#0a0102 100%);padding:80px 0}.sc-gallery-container{width:100%;max-width:1280px;margin:0 auto;padding:0 40px;box-sizing:border-box}.sc-gallery-eyebrow{font-family:Inter,sans-serif;font-size:13px;font-weight:700;letter-spacing:.15em;color:#F2B84B;text-transform:uppercase;text-align:center;margin-bottom:12px}.sc-gallery-title{font-family:var(--mfn-heading-font-family,Cinzel,serif);font-size:clamp(24px,3vw,36px);font-weight:700;color:#fff;line-height:1.2;margin:0 0 56px 0;text-align:center}.sc-gallery-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;margin-bottom:48px}.sc-gallery-card{position:relative;border-radius:16px;overflow:hidden;aspect-ratio:4/3;background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.06);transition:all .3s ease}.sc-gallery-card:hover{border-color:rgba(242,184,75,.3);transform:translateY(-4px);box-shadow:0 20px 40px rgba(0,0,0,.5)}.sc-gallery-card img{width:100%;height:100%;object-fit:cover;display:block;transition:transform .5s ease}.sc-gallery-card:hover img{transform:scale(1.05)}.sc-gallery-card-label{position:absolute;bottom:0;left:0;right:0;padding:40px 20px 16px 20px;background:linear-gradient(to top,rgba(10,1,2,.9)0%,transparent 100%);font-family:Inter,sans-serif;font-size:13px;font-weight:600;color:#fff;letter-spacing:.03em}.sc-gallery-placeholder{background:rgba(255,255,255,.02);border:1px dashed rgba(242,184,75,.15);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:12px;color:rgba(255,255,255,.2)}.sc-gallery-placeholder svg{width:40px;height:40px;opacity:.5}.sc-gallery-placeholder span{font-family:Inter,sans-serif;font-size:12px;font-weight:500;letter-spacing:.05em;text-transform:uppercase}.sc-gallery-cta{text-align:center}.sc-gallery-cta a{display:inline-flex;align-items:center;justify-content:center;gap:10px;padding:16px 32px;border-radius:99px;font-family:Inter,sans-serif;font-weight:800;font-size:13px;letter-spacing:.05em;text-transform:uppercase;text-decoration:none;transition:all .3s ease;background:transparent;color:#F2B84B;border:1px solid rgba(242,184,75,.4)}.sc-gallery-cta a:hover{background:rgba(242,184,75,.1);border-color:#F2B84B;transform:translateY(-3px)}@media(max-width:768px){.sc-gallery-section{padding:60px 0}.sc-gallery-container{padding:0 20px}.sc-gallery-grid{grid-template-columns:1fr 1fr;gap:16px}.sc-gallery-title{margin-bottom:40px}}@media(max-width:480px){.sc-gallery-grid{grid-template-columns:1fr}}</style>'
CSS_F='<style>.sc-faq-section{position:relative;width:100%;background:linear-gradient(180deg,#0a0102 0%,#1a0304 50%,#0a0102 100%);padding:80px 0}.sc-faq-container{width:100%;max-width:800px;margin:0 auto;padding:0 40px;box-sizing:border-box}.sc-faq-title{font-family:var(--mfn-heading-font-family,Cinzel,serif);font-size:clamp(24px,3vw,36px);font-weight:700;color:#fff;line-height:1.2;margin:0 0 56px 0;text-align:center}.sc-faq-list{display:flex;flex-direction:column;gap:12px}.sc-faq-item{background:rgba(255,255,255,.03);border:1px solid rgba(255,255,255,.08);border-radius:12px;overflow:hidden;transition:all .3s ease}.sc-faq-item:hover{border-color:rgba(242,184,75,.15)}.sc-faq-question{width:100%;background:none;border:none;padding:24px 28px;display:flex;align-items:center;justify-content:space-between;gap:16px;cursor:pointer;text-align:left;font-family:Inter,sans-serif;font-size:15px;font-weight:600;color:#fff;line-height:1.4;transition:color .3s ease}.sc-faq-question:hover{color:#F2B84B}.sc-faq-question:focus-visible{outline:2px solid #F2B84B;outline-offset:-2px}.sc-faq-icon{flex-shrink:0;width:20px;height:20px;color:var(--ca-gold-500,#F2B84B);transition:transform .35s ease}.sc-faq-item.active .sc-faq-icon{transform:rotate(45deg)}.sc-faq-item.active .sc-faq-question{color:#F2B84B}.sc-faq-answer{max-height:0;overflow:hidden;transition:max-height .4s ease,padding .4s ease}.sc-faq-item.active .sc-faq-answer{max-height:300px}.sc-faq-answer-inner{padding:0 28px 24px 28px;font-family:Inter,sans-serif;font-size:14px;line-height:1.7;color:rgba(255,255,255,.65)}@media(max-width:768px){.sc-faq-section{padding:60px 0}.sc-faq-container{padding:0 20px}.sc-faq-title{margin-bottom:40px}.sc-faq-question{padding:20px 20px;font-size:14px}.sc-faq-answer-inner{padding:0 20px 20px 20px}}</style>'

def save(p,c):
    with open(p,'w',encoding='utf-8')as f:f.write(c)

# SHOPPING CENTERS
save('solucoes/_blocks/sh_solutions.html',f'<section class="sc-solutions-section">{CSS_S}<div class="sc-solutions-container"><div class="sc-solutions-eyebrow">SOLUÇÕES PARA O SEU SHOPPING</div><h2 class="sc-solutions-title">Experiências completas para cada etapa da campanha de Natal</h2><div class="sc-solutions-grid">{sc(I["star"],"PAPAI NOEL PROFISSIONAL","Papai Noel com treinamento, figurino e interação preparada para encantar famílias e gerar filas de visitação.")}{sc(I["cam"],"CENÁRIOS FOTOGRÁFICOS","Espaços instagramáveis planejados para gerar registros compartilháveis e ampliar o alcance da campanha.")}{sc(I["ppl"],"PERSONAGENS E ATRAÇÕES","Elenco temático, espetáculos, plataforma 360° e experiências interativas para diferentes perfis de público.")}{sc(I["chk"],"OPERAÇÃO COMPLETA","Planejamento, produção, montagem, operação, manutenção e desmontagem com equipe dedicada.")}{sc(I["spk"],"CENOGRAFIA EXCLUSIVA","Projetos cenográficos autorais desenvolvidos para valorizar a arquitetura e identidade do empreendimento.")}{sc(I["clk"],"CAMPANHAS COMPLETAS","Ações integradas do planejamento estratégico ao encerramento, com métricas, relatórios e acompanhamento.")}</div></div></section>')
save('solucoes/_blocks/sh_benefits.html',f'<section class="sc-benefits-section">{CSS_B}<div class="sc-benefits-container"><h2 class="sc-benefits-title">Por que os maiores shoppings escolhem a Criação</h2><div class="sc-benefits-grid">{bc(I["shd"],"30 ANOS DE EXPERIÊNCIA","Referência nacional em projetos natalinos para shopping centers, com milhares de eventos realizados.")}{bc(I["spk"],"PROJETOS EXCLUSIVOS","Cada campanha é desenvolvida sob medida, sem repetir projetos entre empreendimentos concorrentes.")}{bc(I["ppl"],"EQUIPE DEDICADA","Profissionais especializados em cada etapa: criação, produção, operação, manutenção e desmontagem.")}{bc(I["clk"],"OPERAÇÃO CONTÍNUA","Acompanhamento diário durante toda a temporada, com equipe de prontidão para ajustes e manutenção.")}</div></div></section>')
save('solucoes/_blocks/sh_gallery.html',f'<section class="sc-gallery-section">{CSS_G}<div class="sc-gallery-container"><div class="sc-gallery-eyebrow">PROJETOS QUE INSPIRAM</div><h2 class="sc-gallery-title">Experiências criadas para os maiores shoppings do Brasil</h2><div class="sc-gallery-grid">{gi("../assets/images/gallery/papai-noel-shopping-rio-mar-fortaleza-criaacao-entretenimento.webp","Papai Noel no Shopping RioMar Fortaleza — CriaAção Entretenimento",1375,1144)}{gp(I["star"],"Cenário fotográfico")}{gp(I["ppl"],"Personagens e interação")}{gp(I["cam"],"Plataforma 360°")}{gp(I["spk"],"Cenografia exclusiva")}{gp(I["chk"],"Operação em shopping")}</div><div class="sc-gallery-cta"><a href="/portfolio">VER PORTFÓLIO COMPLETO</a></div></div></section>')
save('solucoes/_blocks/sh_faq.html',f'<section class="sc-faq-section">{CSS_F}<div class="sc-faq-container"><h2 class="sc-faq-title">Tudo o que você precisa saber antes de contratar</h2><div class="sc-faq-list">{fq("Quanto tempo antes a Criação precisa ser contratada?","Recomendamos que o contato seja feito com pelo menos seis meses de antecedência para garantir o desenvolvimento de um projeto exclusivo e a disponibilidade de agenda.")}{fq("O projeto pode ser adaptado ao tamanho do shopping?","Sim. Desenvolvemos projetos para empreendimentos de diferentes portes, adequando escala, formato, atrações e investimento.")}{fq("A Criação desenvolve projetos para mais de um ano?","Sim. Podemos planejar campanhas para múltiplas temporadas, com renovação de conceitos, cenografia e atrações.")}{fq("A equipe cuida da manutenção durante a campanha?","Sim. Mantemos equipe dedicada para acompanhamento diário, manutenção de cenografia, figurinos e operação durante toda a temporada.")}{fq("Vocês atendem shoppings em qualquer região do Brasil?","Sim. Atendemos empreendimentos em todo o território nacional, com planejamento logístico e equipe local ou deslocada conforme a necessidade do projeto.")}{fq("É possível incluir ações promocionais com lojistas?","Sim. Podemos desenvolver estratégias integradas que envolvam sorteios, campanhas, ativações e benefícios para lojistas e clientes.")}</div></div>{FS}</section>')

# GESTÃO PÚBLICA
save('solucoes/_blocks/gp_solutions.html',f'<section class="sc-solutions-section">{CSS_S}<div class="sc-solutions-container"><div class="sc-solutions-eyebrow">SOLUÇÕES PARA O PODER PÚBLICO</div><h2 class="sc-solutions-title">Atrações que mobilizam a cidade e aquecem a economia local</h2><div class="sc-solutions-grid">{sc(I["star"],"ILUMINAÇÃO PÚBLICA","Projetos de iluminação natalina para ruas, avenidas, praças e monumentos, com tecnologia e eficiência energética.")}{sc(I["hom"],"PRAÇAS E ESPAÇOS","Vilas de Natal, presépios vivos, árvores e cenografia para espaços de convivência da cidade.")}{sc(I["ppl"],"PERSONAGENS E ESPETÁCULOS","Elenco temático, apresentações culturais, corais e intervenções artísticas em espaços públicos.")}{sc(I["cam"],"ESPAÇOS FOTOGRÁFICOS","Cenários instagramáveis instalados em pontos estratégicos para moradores e turistas.")}{sc(I["chk"],"OPERAÇÃO E SEGURANÇA","Planejamento operacional completo com atenção a normas públicas, acessibilidade e segurança.")}{sc(I["clk"],"PROJETOS PLURIANUAIS","Parcerias de longo prazo com renovação anual de conceitos, atrações e experiências temáticas.")}</div></div></section>')
save('solucoes/_blocks/gp_benefits.html',f'<section class="sc-benefits-section">{CSS_B}<div class="sc-benefits-container"><h2 class="sc-benefits-title">Por que cidades de todo o Brasil escolhem a Criação</h2><div class="sc-benefits-grid">{bc(I["shd"],"EXPERIÊNCIA COMPROVADA","Mais de 30 anos realizando projetos natalinos para administrações públicas em todo o país.")}{bc(I["map"],"IMPACTO REGIONAL","Projetos que aquecem o comércio, fomentam o turismo e geram empregos temporários na região.")}{bc(I["ppl"],"ACESSO GRATUITO","Experiências planejadas para serem acessíveis a toda a população, sem cobrança de ingressos.")}{bc(I["clk"],"EXECUÇÃO COMPLETA","Da concepção à desmontagem, com equipe dedicada, cronograma público e prestação de contas.")}</div></div></section>')
save('solucoes/_blocks/gp_gallery.html',f'<section class="sc-gallery-section">{CSS_G}<div class="sc-gallery-container"><div class="sc-gallery-eyebrow">CIDADES QUE ENCANTAM</div><h2 class="sc-gallery-title">Projetos que transformaram espaços públicos em destinos de Natal</h2><div class="sc-gallery-grid">{gi("../assets/images/gallery/prefeitura_natal_1783728927398.webp","Decoração natalina em espaço público — CriaAção Entretenimento")}{gp(I["hom"],"Vila de Natal na praça")}{gp(I["star"],"Iluminação de avenidas")}{gp(I["ppl"],"Presépio vivo")}{gp(I["cam"],"Cenário fotográfico público")}{gp(I["chk"],"Espetáculo cultural")}</div><div class="sc-gallery-cta"><a href="/portfolio">VER PORTFÓLIO COMPLETO</a></div></div></section>')
save('solucoes/_blocks/gp_faq.html',f'<section class="sc-faq-section">{CSS_F}<div class="sc-faq-container"><h2 class="sc-faq-title">Tudo o que a administração pública precisa saber</h2><div class="sc-faq-list">{fq("A Criação participa de licitações públicas?","Sim. A empresa está apta a participar de processos licitatórios e atende aos requisitos legais para contratação pela administração pública.")}{fq("O projeto pode ser adaptado ao orçamento público?","Sim. Desenvolvemos propostas adequadas a diferentes escalas de investimento, do bairro à cidade, sempre com qualidade e planejamento.")}{fq("Quanto tempo antes o planejamento deve começar?","Recomendamos que o contato seja iniciado com pelo menos oito meses de antecedência para projetos públicos de grande escala.")}{fq("A Criação cuida da manutenção durante a temporada?","Sim. Mantemos equipe dedicada para manutenção diária da cenografia, iluminação, personagens e atrações durante todo o período.")}{fq("É possível incluir atrações culturais e apresentações?","Sim. O projeto pode integrar corais, orquestras, grupos teatrais, artistas locais e intervenções culturais programadas.")}{fq("Vocês atendem cidades de qualquer porte?","Sim. Desenvolvemos projetos para diferentes escalas, de pequenos municípios a grandes capitais, adequando formato e investimento.")}</div></div>{FS}</section>')

# ESCOLAS
save('solucoes/_blocks/esc_solutions.html',f'<section class="sc-solutions-section">{CSS_S}<div class="sc-solutions-container"><div class="sc-solutions-eyebrow">EXPERIÊNCIAS PARA A ESCOLA</div><h2 class="sc-solutions-title">Formatos adaptados à rotina e ao espaço escolar</h2><div class="sc-solutions-grid">{sc(I["star"],"VISITA DO PAPAI NOEL","Encontro preparado para diferentes faixas etárias, com interação mediada pelos educadores e respeito ao ritmo das crianças.")}{sc(I["cam"],"ESPAÇOS FOTOGRÁFICOS","Cenários planejados para registros da turma, dos alunos com o Papai Noel e das famílias durante o evento.")}{sc(I["ppl"],"PERSONAGENS DE APOIO","Mamãe Noel, duendes e outros personagens para tornar a experiência mais rica e envolvente.")}{sc(I["chk"],"ORGANIZAÇÃO POR TURMAS","Planejamento de horários e fluxo para atender diferentes grupos sem sobrecarregar o ambiente escolar.")}{sc(I["gft"],"KITS E ATIVIDADES","Materiais complementares que podem ser integrados à experiência de acordo com o formato escolhido.")}{sc(I["clk"],"PLANEJAMENTO CONJUNTO","Cada projeto é construído em parceria com a direção e a equipe pedagógica da instituição.")}</div></div></section>')

# EMPRESAS E CORPORATIVO
save('solucoes/_blocks/emp_benefits.html',f'<section class="sc-benefits-section">{CSS_B}<div class="sc-benefits-container"><h2 class="sc-benefits-title">Por que empresas de todo o Brasil confiam na Criação</h2><div class="sc-benefits-grid">{bc(I["shd"],"EXPERTISE COMPROVADA","Mais de 30 anos desenvolvendo experiências para marcas e corporações de diferentes portes e segmentos.")}{bc(I["spk"],"PROJETO EXCLUSIVO","Cada experiência é desenvolvida sob medida, alinhada à identidade, aos valores e aos objetivos da sua empresa.")}{bc(I["ppl"],"OPERAÇÃO COMPLETA","Equipe dedicada para planejamento, produção, coordenação, execução e desmontagem do evento.")}{bc(I["clk"],"FLEXIBILIDADE DE FORMATO","Atendemos confraternizações, convenções, campanhas internas, ações promocionais e eventos para famílias.")}</div></div></section>')

print("All blocks created.")
print(f"sh_solutions: {len(open('solucoes/_blocks/sh_solutions.html').read())} bytes")
print(f"sh_benefits: {len(open('solucoes/_blocks/sh_benefits.html').read())} bytes")
print(f"sh_gallery: {len(open('solucoes/_blocks/sh_gallery.html').read())} bytes")
print(f"sh_faq: {len(open('solucoes/_blocks/sh_faq.html').read())} bytes")
print(f"gp_solutions: {len(open('solucoes/_blocks/gp_solutions.html').read())} bytes")
print(f"gp_benefits: {len(open('solucoes/_blocks/gp_benefits.html').read())} bytes")
print(f"gp_gallery: {len(open('solucoes/_blocks/gp_gallery.html').read())} bytes")
print(f"gp_faq: {len(open('solucoes/_blocks/gp_faq.html').read())} bytes")
print(f"esc_solutions: {len(open('solucoes/_blocks/esc_solutions.html').read())} bytes")
print(f"emp_benefits: {len(open('solucoes/_blocks/emp_benefits.html').read())} bytes")
